"""Deterministic Forge Agent foundations."""

# The providers and decisions subpackages are imported here on purpose. They
# were previously unreferenced, so their undeclared third-party dependencies
# went unnoticed while the test suite stayed green. Importing them means a
# missing dependency fails at import time, where CI can see it.

from .config import load_env
from .context_engine import (
    AssembledContext,
    ContextAssembler,
    ContextBudget,
    ContextItem,
    ContextProvenance,
    SourceType,
)
from .decisions import JevClient, RiskLevel
from .execution_loop import (
    AgentRole,
    AuditReport,
    BuilderHandoff,
    BuildPacket,
    CandidateInspection,
    ContextIdentity,
    DiscoveryVerdict,
    EvidenceReceipt,
    ExecutionLoop,
    ImplementationVerdict,
    LoopState,
    MergeEligibility,
    OwnerAuthorization,
)
from .governor import (
    Budget,
    BudgetDimension,
    BudgetLedger,
    GovernorError,
    SpendOutcome,
    SpendReceipt,
)
from .learning import (
    ApplicationRecord,
    CandidateLesson,
    LearningError,
    Lesson,
    LessonDecision,
    LessonScope,
    LessonState,
    LessonStore,
    Measurement,
    MeasurementVerdict,
    Metric,
    MetricDirection,
    OutcomeRecord,
    RetrievalRecord,
    failure_signature,
)
from .ledger_store import LedgerStore
from .product_brain import (
    Assumption,
    AssumptionStatus,
    DecisionRecord,
    DiscoveryRecord,
    FinishContract,
    Invariant,
    NorthStar,
    ProductBrain,
    Requirement,
    RequirementStatus,
)
from .providers import Capability, ModelProvider, ProviderError, SchemaInvalidError
from .stuck import (
    AttemptRecord,
    Rung,
    Strategy,
    StuckDetector,
    StuckError,
    StuckReason,
    StuckVerdict,
    patch_hash,
)
from .trust_kernel import (
    Authority,
    AuthorityGrant,
    CandidateIdentity,
    CandidateValidation,
    CompletionEvaluation,
    DiscoveryAuthorization,
    EffectDisposition,
    EvidenceStatus,
    ForgeError,
    Ledger,
    LedgerCheckpoint,
    MissionState,
    ReconciliationEvidence,
    RepositoryIdentity,
    TransitionEvidence,
    TrustKernel,
)

__all__ = [
    "AgentRole",
    "ApplicationRecord",
    "AssembledContext",
    "Assumption",
    "AssumptionStatus",
    "AttemptRecord",
    "AuditReport",
    "Budget",
    "BudgetDimension",
    "BudgetLedger",
    "CandidateLesson",
    "Capability",
    "Authority",
    "AuthorityGrant",
    "BuildPacket",
    "BuilderHandoff",
    "CandidateIdentity",
    "CandidateInspection",
    "CandidateValidation",
    "CompletionEvaluation",
    "ContextAssembler",
    "ContextBudget",
    "ContextItem",
    "ContextProvenance",
    "ContextIdentity",
    "DecisionRecord",
    "DiscoveryAuthorization",
    "DiscoveryRecord",
    "DiscoveryVerdict",
    "EffectDisposition",
    "EvidenceReceipt",
    "EvidenceStatus",
    "ExecutionLoop",
    "FinishContract",
    "ForgeError",
    "GovernorError",
    "JevClient",
    "ImplementationVerdict",
    "Invariant",
    "LearningError",
    "Ledger",
    "load_env",
    "LedgerStore",
    "LedgerCheckpoint",
    "Lesson",
    "LessonDecision",
    "LessonScope",
    "LessonState",
    "LessonStore",
    "LoopState",
    "Measurement",
    "MeasurementVerdict",
    "MergeEligibility",
    "Metric",
    "MetricDirection",
    "MissionState",
    "ModelProvider",
    "NorthStar",
    "OutcomeRecord",
    "OwnerAuthorization",
    "ProductBrain",
    "ProviderError",
    "ReconciliationEvidence",
    "RepositoryIdentity",
    "Requirement",
    "RequirementStatus",
    "RetrievalRecord",
    "RiskLevel",
    "Rung",
    "SchemaInvalidError",
    "SourceType",
    "SpendOutcome",
    "SpendReceipt",
    "Strategy",
    "StuckDetector",
    "StuckError",
    "StuckReason",
    "StuckVerdict",
    "TransitionEvidence",
    "TrustKernel",
    "failure_signature",
    "patch_hash",
]
